#server.servlet.context-path=/bangalo

#spring.view.prefix: /WEB-INF/jsp/
#spring.view.suffix: .jsp

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

debug: true
