server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging:
  level:
    org.springframework.web: DEBUG
